apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /post/?(.*)
            backend:
              serviceName: posts
              servicePort: 5001
