apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments-container
          image: varma1909/comments-microservice
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          # ports:
          # - containerPort: <Port>
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  selector:
    app: comments
  ports:
    - port: 5002
      targetPort: 5002
