apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-query
spec:
  selector:
    matchLabels:
      app: print-query
  template:
    metadata:
      labels:
        app: print-query
    spec:
      containers:
        - name: print-query
          image: varma1909/print-query-service
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          # ports:
          # - containerPort: <Port>
---
apiVersion: v1
kind: Service
metadata:
  name: print-query-service
spec:
  selector:
    app: print-query
  ports:
    - port: 5003
      targetPort: 5003
